// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace GuidSqlInsert
{
    internal sealed partial class Vsix
    {
        public const string Id = "GuidSqlInsert.fc45065e-8e8a-4147-be46-cd48e93e638c";
        public const string Name = "GuidSqlInsert";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Yui Han";
        public const string Tags = "";
    }
}
